const state = { name: 'Alicia James', handle: '@alicia', currency: '$', saved: 75, goal: 200, timeframe: 180, deposit: 20, checkinOffset: 0 };
const $ = (selector) => document.querySelector(selector);
const money = (value) => `${state.currency}${Number(value).toFixed(2)}`;
const hasProfile = () => localStorage.getItem('wispace-profile-created') === 'true';

function showScreen(id) { document.querySelectorAll('.screen').forEach((screen) => screen.classList.remove('active')); $(`#${id}`).classList.add('active'); }
function showPage(id) { document.querySelectorAll('.page').forEach((page) => page.classList.remove('active-page')); $(`#${id}`).classList.add('active-page'); document.querySelectorAll('.bottom-nav button').forEach((button) => button.classList.toggle('active', button.dataset.page === id)); }
function updateHome() {
  const percentage = Math.min((state.saved / state.goal) * 100, 100);
  $('#progress-ring').style.setProperty('--progress', `${percentage}%`); $('#saved-value').textContent = money(state.saved); $('#goal-value').textContent = money(state.goal); $('#deposit-label').textContent = money(state.deposit); $('#next-deposit').textContent = money(state.deposit); $('#month-saved').textContent = money(state.saved);
  $('#pace-copy').textContent = percentage >= 100 ? 'Goal reached - what a feeling' : percentage > 35 ? 'You are right on pace' : 'Small steps still count';
}
function renderCheckins() { const track = $('#checkin-track'); track.innerHTML = ''; for (let index = 0; index < 7; index += 1) { const day = state.checkinOffset + index + 1; const card = document.createElement('button'); card.className = `day-card ${day < 3 ? 'done' : ''} ${day === 3 ? 'today' : ''}`; card.innerHTML = `<span>Day ${day}</span><strong>${money(state.deposit).replace('.00', '')}</strong>`; card.addEventListener('click', () => { card.classList.toggle('done'); card.classList.remove('today'); }); track.appendChild(card); } }
function renderGoal() { const daily = state.goal / state.timeframe; const weekly = daily * 7; const fortnight = daily * 14; const monthly = daily * 30; const sixMonths = daily * 180; const yearly = daily * 365; $('#cadence-value').textContent = `${money(daily)} / day`; $('#cadence-chips').innerHTML = [['Daily', daily], ['Weekly', weekly], ['Every 2 weeks', fortnight], ['Monthly', monthly], ['6 months', sixMonths], ['Yearly', yearly]].map(([label, value], index) => `<button class="${index === 1 ? 'recommended' : ''}" type="button">${label} ${money(value)}</button>`).join(''); $('#goal-list').innerHTML = `<article class="goal-item"><header><span>Active goal</span><span>${Math.round((state.saved / state.goal) * 100)}%</span></header><strong class="goal-amount">${money(state.saved)}</strong><small>of ${money(state.goal)} · ${state.timeframe} days left in plan</small><div class="bar"><i style="width:${Math.min((state.saved / state.goal) * 100, 100)}%"></i></div></article>`; }
function renderTransactions() { const entries = [['Payday', 'Today', '+$3,000', 'green'], ['Market', 'Today', '-$78', 'red'], ['Cafe', 'Yesterday', '-$16', 'gold'], ['Freelance', 'Yesterday', '+$420', 'purple']]; $('#transactions').innerHTML = entries.map(([name, date, amount, tone]) => `<div class="transaction"><span class="transaction-icon ${tone}">□</span><div><strong>${name}</strong><small>${date}</small></div><span class="amount ${amount[0] === '+' ? 'positive' : 'negative'}">${amount}</span></div>`).join(''); $('#history-saved').textContent = money(state.saved + 1185); }
function hydrateProfile() { $('#profile-name').textContent = state.name; $('#profile-handle').textContent = state.handle; $('#avatar').textContent = state.name.charAt(0).toUpperCase(); $('#profile-currency').value = state.currency; $('#currency-symbol').textContent = state.currency; }
function refresh() { updateHome(); renderCheckins(); renderGoal(); renderTransactions(); hydrateProfile(); }

document.querySelectorAll('[data-page]').forEach((button) => button.addEventListener('click', () => showPage(button.dataset.page)));
document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'start' || action === 'signin') showScreen('signin-view'); if (action === 'welcome') showScreen('welcome-view'); if (action === 'deposit') $('#deposit-modal').classList.add('open'); if (action === 'close-modal') $('#deposit-modal').classList.remove('open'); if (action === 'shift-checkins') { state.checkinOffset += 4; renderCheckins(); } if (action === 'new-goal') { showPage('goals-page'); $('#target-input').focus(); } }));
$('#profile-form').addEventListener('submit', (event) => { event.preventDefault(); const firstName = $('#first-name-input').value.trim(); const lastName = $('#last-name-input').value.trim(); state.name = $('#name-input').value.trim() || `${firstName} ${lastName}`; state.handle = `@${firstName.toLowerCase()}`; state.currency = $('#currency-input').value; localStorage.setItem('wispace-profile-created', 'true'); refresh(); showScreen('app-view'); });
$('#confirm-deposit').addEventListener('click', () => { const amount = Number($('#deposit-input').value); if (amount > 0) { state.saved += amount; state.deposit = amount; $('#deposit-modal').classList.remove('open'); refresh(); } });
document.querySelectorAll('.deposit-suggestions button').forEach((button) => button.addEventListener('click', () => { $('#deposit-input').value = button.dataset.amount; }));
['target-input', 'timeframe-input'].forEach((id) => $(`#${id}`).addEventListener('input', () => { state.goal = Number($('#target-input').value) || 1; state.timeframe = Number($('#timeframe-input').value); renderGoal(); }));
$('#save-goal').addEventListener('click', () => { state.goal = Number($('#target-input').value) || 1; state.timeframe = Number($('#timeframe-input').value); updateHome(); renderGoal(); showPage('home-page'); });
$('#profile-currency').addEventListener('change', (event) => { state.currency = event.target.value; refresh(); });
let pointerStart = null; $('#checkin-track').addEventListener('pointerdown', (event) => { pointerStart = event.clientX; }); $('#checkin-track').addEventListener('pointerup', (event) => { if (pointerStart !== null && Math.abs(event.clientX - pointerStart) > 40) { state.checkinOffset = Math.max(0, state.checkinOffset + (pointerStart > event.clientX ? 3 : -3)); renderCheckins(); } pointerStart = null; });
refresh();
if (hasProfile()) showScreen('app-view');